[project]
name = "google-books"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "lxml>=5.3.1",
    "pydantic>=2.10.6",
    "pyright>=1.1.396",
    "resync>=2.0.1",
]
